[package]
name = "ecdh_decryption_verifier"
type = "lib"
authors = ["Rajesh Kanna"]
compiler_version = ">=0.22.0"

[dependencies]
noir_bigint_curves = { path = "../noir_bigint/crates/curves" }
noir_biguint = { path = "../noir_bigint/crates/biguint" }
noir_bigint_primefield = { path = "../noir_bigint/crates/primefield" }